### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tibbben** [Geospatial-Digital-Special-Collections/docs#2]
- [ ] formalize collection level metadata
- [ ] provide a mechanism in the front end to see collection level metadata
- [ ] use collections metadata to populate collections menu in front end
- [ ] create collection maps
- [ ] WMS, WFS??
- [ ] raster tiling apart from data layer (with symbology)
