### ISSUE TITLE
Datasets TODO

### ISSUE THREAD

**Issue by tibbben** [Geospatial-Digital-Special-Collections/docs#3]
- [ ] public housing layer for GDSC ... http://flhousingdata.shimberg.ufl.edu then blended with RER of miami dade county https://www.miamidade.gov/global/economy/home.page
- [x] Miami-Dade [WaterP](https://gis-mdc.opendata.arcgis.com/datasets/bf9de3192c9c4e458d1453f6d4c88d6c_0/explore) layer
- [x] Miami-Dade [Street](https://gis-mdc.opendata.arcgis.com/datasets/a7e9449c8ec04bd39fb952e66e341442_0/explore) layer
- [x] Subset of street layer with only highways and main roads (consider a dissolve on name and type?)
- [x] Protected areas (perhaps all of Florida, NPS, or the [Florida Natural Areas Inventory](https://www.fnai.org/publications/gis-data))
- [x] all the 5 categories of the slosh models (add vector capability)
- [x] Miami Dade building footprints
- [x] Miami-Dade Stormwater Line
- [x] Miami-Dade DOH septic system (look at DOH website as well)
- [x] Miami-Dade Storm Surge Planning Zones
- [ ] humidity
- [ ] Pump Stations
- [x] UV or solar irradiance layer?? Landsat API https://www.usgs.gov/landsat-missions/landsat-data-access
- [ ] IQ air API https://www.iqair.com/us/commercial-air-quality-monitors/api
- [x] howloud.com API https://api.howloud.com/docs/
- [ ] water quality from MDC?
- [ ] Electric Lines
- [ ] Sewer Mains
- [ ] manhole covers
- [ ] hurricane tracks
- [ ] rainfall
- [ ] can we calculate albedo from something?
- [ ] building violations - EPA ECHO - https://echo.epa.gov
- [ ] look at HIFLD: https://hifld-geoplatform.hub.arcgis.com/pages/hifld-open

**Comment by tibbben** [comment]
make temporary parcels_camp layer with three dependencies
- protected areas
- streets
- water

**Comment by tibbben** [comment]
QC after load is complete:
- check landing page for data
- check analytic functions working (change url as below)
   https://gdsc.idsc.miami.edu/functions/ ---> http://localhost:3000/
- check etl documentation

**Comment by tibbben** [comment]
See notes for Azizi and Sade ....

**Comment by tibbben** [comment]
Update Structure and geometry in ACS layer to (respectively):
vector, polygon
