### ISSUE TITLE
Raster TODO

### ISSUE THREAD

**Issue by tibbben** [Geospatial-Digital-Special-Collections/docs#5]
- [ ]  WMS, WFS??
- [ ]  raster tiling apart from data layer (with symbology)

**Comment by tibbben** [comment]
design raster proximity layers as dependencies on vector geometries ...

- [ ] need for custom ETL function to calculate proximity raster (likely as a postGIS function)
- [ ] ends with two layers, the vector dependency and the raster product
- [ ] need to have raster resolution/cell size in metadata
