### ISSUE TITLE
Metadata TODO

### ISSUE THREAD

**Issue by tibbben** [Geospatial-Digital-Special-Collections/docs#7]
- [ ] metadata as object store on GitHub, and a running database for loaded ...
- [ ] proof read everything from search app
- [ ] move columns metadata to attributes, think about length of int and char columns

**Comment by tibbben** [comment]
perhaps useful metadata links

- LOC subject headings: https://authorities.loc.gov/cgi-bin/Pwebrecon.cgi?DB=local&PAGE=First
- MARC: https://www.oclc.org/bibformats/en.html
- datacite schema: https://schema.datacite.org/meta/kernel-4.4/
- https://www.iso.org/obp/ui/#iso:std:iso:19115:-1:ed-1:v1:en
- https://www.iso.org/obp/ui/#iso:std:iso:19119:ed-2:v1:en
- https://www.iso.org/standard/53798.html
- https://www.fgdc.gov/metadata/geospatial-metadata-standards#nap
- https://www.w3.org/TR/vocab-data-cube/
- https://www.dublincore.org/specifications/dublin-core/dcmi-terms/
- https://sdmx.org/?page_id=2561
- https://www.w3.org/TR/vocab-dcat-3/
- https://semiceu.github.io/GeoDCAT-AP/drafts/latest/

**Comment by tibbben** [comment]
With regard to authoring JSON-LD I've been working on a new flow using RML (rml.io).  So we could take CSV or XML output from Google Forms or Kobo ([https://www.kobotoolbox.org/](https://www.kobotoolbox.org/)) and convert that to triples/JSON-LD with RML processors.  You can see examples of this at [https://rml.io/docs/rml/tutorials/xml/](https://rml.io/docs/rml/tutorials/xml/).   Then connect that with SHACL shapes we build for validation.   I've not worked with LinkML, though I am aware of it.   Steve, didn't the samples group use LinkML, how was the developer experience with it?

from Doug Fils <doug@fils.network>
