### ISSUE TITLE
ArcGIS server/portal TODO

### ISSUE THREAD

**Issue by tibbben** [Geospatial-Digital-Special-Collections/docs#8]
- [ ] double check all point layers in ArcGIS Pro ()can be a part of creating collection maps)
- [ ] add all resilience MDC layers to the server and portal
- [ ] double check all service definition files are on box (correct names)
